# Generated by Django 5.0.9 on 2024-11-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_project_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
    ]
