# Generated by Django 5.0.9 on 2024-11-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_project_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='active', max_length=20),
        ),
    ]
