# Generated by Django 5.0.9 on 2024-11-21 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usecases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('diagram_data', models.JSONField(blank=True, help_text='Stores JSON representation of the diagram.', null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='usecases.usecase')),
            ],
        ),
    ]
